services:
  postgres:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: eh-app-postgres
    environment:
      POSTGRES_DB: "event_horizon"
      POSTGRES_USER: "event_horizon_user"
      POSTGRES_PASSWORD: "eventhorizon"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U event_horizon_user -d event_horizon"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: eh-app-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://event_horizon_user:eventhorizon@postgres:5432/event_horizon
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: eh-app-frontend
    ports:
      - "5173:5173"
    environment:
      - DOCKER_ENV=true
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data: