version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: event-horizon-postgres
    environment:
      POSTGRES_DB: "event_horizon"
      POSTGRES_USER: "event_horizon_user"
      POSTGRES_PASSWORD: "eventhorizon"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U event_horizon_user -d event_horizon"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: